image:  linagora/node-test-base:8-with-chrome

services:
  - linagora/janus-gateway:latest

stages:
  - test

test:
  stage: test
  tags:
    - docker
  variables:
    JANUS_TEST_URL: linagora__janus-gateway
  script:
    - npm install
    - npm prune
    - bower i --allow-root
    - grunt --chunk=1
